* Emacs 24 Config
** General Notes
   Packages come from [[https://github.com/dimitri/el-get][el-get]], which is built on the ELPA manager included in Emacs 24.
   Package libraries in use: [[http://tromey.com/elpa/"][ELPA]], [[http://elpa.gnu.org/packages/][gnu]], [[http://marmalade-repo.org/packages/][marmalade]], and [[http://tromey.com/elpa/][tromey]].
** Initial Setup
   1. > cd emacs.d
      > git submodule init
      > git submodule update
   2. Open emacs, maybe several times to get all the packages loaded and installed.

** Outside dependencies
*** TAGS
    I use ctags to generate a TAGS file for Ruby. This allows following a method name to its definitation
    1. get ctags that supports Ruby.  The one from homebrew does.
       > brew install ctags
    2. A couple bash aliases to help
       - alias ctags="`brew --prefix`/bin/ctags"
       - alias rtags="ctags -a -e -f TAGS --tag-relative -R . --exclude=-.git --exclude=log *"
    3. M-. your bad self
*** Aspell
    If you want to use the spell check (ispell), you'll need you some aspell. Brew again:
    > brew install aspell --lang=EN
*** Bazaar
    You'll need this if you are looking to get any number of Emacs packages. It's the source control used by a number of them.
    > brew install bzr
*** Passwords
    You can have a file encrypted that you store passwords and the like in.
    The setup I have asked for your password when emacs loads. Doesn't have to be that way.
    1. > brew isntall gnupg
    2. Any file with the extension .gpg will be encrypted. It'll give you options to encrypt.
    3. I use key-value variables:
       (setq blog-login "foo"
             blog-passw "bar)
       Elsewhere:
       (setq blogger-server-username blog-login) ...
**** Some links to help get it setup
     - [[http://emacs-fu.blogspot.com/2011/02/keeping-your-secrets-secret.html][emacs-fu how-to]]
     - [[http://quantumlab.net/pine_privacy_guard/howto_setup_gpg.html][GNU PG instructions]]

*** multimarkdown
    If you 'brew install multimarkdown', you can generate html from a markdown file. (C-c C-c m)
